## In this code we have install docker and important pack and also run jenkins as docker container

---
- name: Install Docker and Jenkins
  hosts: dev  
  become: true
  gather_facts: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker.io

    - name: create docker volume 
      shell: docker volume create jenkins_data    

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Download and run Jenkins Docker container
      shell: docker run -d --name jenkins -v jenkins_data:/var/jenkins_home -v /var/lib/docker.sock:/var/lib/docker.sock -v $(which docker):/usr/lib/docker -p 8080:8080 jenkins/jenkins:lts
        
